Update some commands name from nextcloud to lxdmosaic

diff --git a/src/apache/bin/run-httpd b/src/apache/bin/run-httpd
--- a/src/apache/bin/run-httpd
+++ b/src/apache/bin/run-httpd
@@ -6,10 +6,10 @@
 mkdir -p "$SNAP_DATA/apache/logs"
 chmod 750 "$SNAP_DATA/apache/logs"
 
-# Make sure Nextcloud is installed and running
-echo "Making sure nextcloud is setup..."
-# if ! setup-nextcloud; then
-# 	echo "Failed to setup nextcloud"
+# Make sure LxdMosaic is installed and running
+echo "Making sure lxdmosaic is setup..."
+# if ! setup-lxdmosaic; then
+# 	echo "Failed to setup lxdmosaic"
 #         exit 1
 # fi
 
