Got this to the point where it appears to be setup errors (composer etc)

diff --git a/src/apache/bin/run-httpd b/src/apache/bin/run-httpd
--- a/src/apache/bin/run-httpd
+++ b/src/apache/bin/run-httpd
@@ -8,10 +8,10 @@ chmod 750 "$SNAP_DATA/apache/logs"
 
 # Make sure Nextcloud is installed and running
 echo "Making sure nextcloud is setup..."
-if ! setup-nextcloud; then
-	echo "Failed to setup nextcloud"
-        exit 1
-fi
+# if ! setup-nextcloud; then
+# 	echo "Failed to setup nextcloud"
+#         exit 1
+# fi
 
 echo "All set! Running httpd..."
 
